Ready for review
IvanDerlich/UsingBootstrap pull request #5
Opened 2019-08-07 07:01 UTC by IvanDerlich

2019-08-07 07:30 UTC, bolah2009 commented
Currently under review

2019-08-07 08:06 UTC, bolah2009 requested changes
## Nice Job [Ivan](../../) :clap: 

Awesome job so far, the [clone](https://raw.githack.com/IvanDerlich/UsingBootstrap/development/index.html) looks good to me and  responsive.. :clap:

However, use more of bootstrap as pointed out in [this comment]() and all other occurrences, make the page more responsive and make the navbar fixed as in the [original site](https://www.newsweek.com/), this is to make the homepage and website menu accessibility anywhere on the page especially for long websites which is the case in this website. See below for illustration:

|Current|Preffered|
| :-----: | :------: |
| ![newsweek fix navbar cureent](https://user-images.githubusercontent.com/36057474/62605498-242c7300-b8f2-11e9-9b90-c3062ce8f0b3.gif) | ![newsweek fix navbar preffred](https://user-images.githubusercontent.com/36057474/62586327-fbd25380-b8b4-11e9-92bd-7247ab96a9ca.gif) |
| ![newsweek navbar current](https://user-images.githubusercontent.com/36057474/62605659-79688480-b8f2-11e9-8a0c-696f0f641308.png) | ![newsweek preffered space](https://user-images.githubusercontent.com/36057474/62605572-56d66b80-b8f2-11e9-80a2-2fd229f4c370.png)   |

Also, check [these warnings](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2FIvanDerlich%2FUsingBootstrap%2Fdevelopment%2Findex.html) on HTML Validator.

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-08-07 08:06 UTC, bolah2009 commented on assets/styles/fonts.css
> +} */
`REQUIRED`

Consider deleting commented out codes. If you need to review a previous version of your code, use git history.

2019-08-07 08:06 UTC, bolah2009 commented on assets/styles/footer.css
> +    /* align-items: flex-end; */
`REQUIRED`

Consider deleting commented out codes. If you need to review a previous version of your code, use git history.

2019-08-07 08:06 UTC, bolah2009 commented on index.html
> +                    <h1 class="title1 title2 col-7">Fox News Host Shepard Smith Delivers Emotional Statement on Gun Violence</h1>
"`SUGGESTION`

Consider using `h2-h6` element here instead. `<h1>` should be used only as a top-level heading. 

> Using only h1 elements in a HTML document results in a flat document outline as heading element semantics are conveyed to users as per the numeric in the heading element tag name.

Learn more [here](https://www.w3.org/wiki/HTML/Usage/Headings/h1only)"

2019-08-07 08:06 UTC, bolah2009 commented on assets/styles/nav.css
> +    justify-content: space-between;
`REQUIRED`

Consider using a Bootstrap class name for this selector element and in all other occurrences.

2019-08-07 08:06 UTC, bolah2009 commented on assets/styles/nav.css
> +        display: none;
`REQUIRED`

Consider using a Bootstrap class name for this selector element and in all other occurrences.

2019-08-07 19:53 UTC, IvanDerlich commented on assets/styles/nav.css
> +        display: none;
Done

2019-08-07 19:53 UTC, IvanDerlich commented on assets/styles/nav.css
> +    justify-content: space-between;
Done

2019-08-07 19:53 UTC, IvanDerlich commented on index.html
> +                    <h1 class="title1 title2 col-7">Fox News Host Shepard Smith Delivers Emotional Statement on Gun Violence</h1>
Thanks

2019-08-07 19:53 UTC, IvanDerlich commented on assets/styles/footer.css
> +    /* align-items: flex-end; */
Done

2019-08-07 19:54 UTC, IvanDerlich commented on assets/styles/fonts.css
> +} */
DOne

2019-08-08 00:03 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-08 00:14 UTC, Torres-ssf commented
### Nice job :clap: 

\[OPTIONAL\]

- [ ] It's best practice to use the `footer` tag instead div for the footer

I'm giving this project a :+1: . You can merge to master now.

2019-08-08 03:48 UTC, merged